apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-0w3f
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-swuy-tenant/rhtap-demo-app/hacbs-test-project-0w3f@sha256:a9da6df2ed92f2cd71c31b0c3f7c93ef0b815707698a5c6e8cba44c5a7d6f32d
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
