apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-0w3f
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-swuy-tenant/rhtap-demo-app/hacbs-test-project-0w3f@sha256:a81655c652ef6a687ff09f00f464740e63439e2665c0a685465309184cb0f641
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
