apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-0w3f
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-0w3f
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-0w3f
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-0w3f
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-0w3f
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-swuy-tenant/rhtap-demo-app/hacbs-test-project-0w3f@sha256:a81655c652ef6a687ff09f00f464740e63439e2665c0a685465309184cb0f641
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
